---
abstract: 'Perl Open Report Framework: Fast flexible reports of any format using any input, easy to enhance at runtime'
author:
  - 'Ralf Peine <ralf.peine@jupiter-programs.de>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Report-Porf
no_index:
  directory:
    - t
    - inc
requires: {}
version: 2.001
